---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: livefpl
  name: livefpl
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: livefpl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: livefpl
    spec:
      containers:
      - args: []
        env: []
        image: ghcr.io/paulrudin/livefpl:0.0.22
        imagePullPolicy: IfNotPresent
        name: livefpl
        ports:
        - containerPort: 8000
          name: http
        stdin: false
        tty: false
        volumeMounts: []
      imagePullSecrets:
      - name: ghcrcred
      initContainers: []
      terminationGracePeriodSeconds: 30
      volumes: []
