---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: livefpl
  name: livefpl
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: livefpl
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        name: livefpl
    spec:
      containers:
      - args: []
        env: []
        image: ghcr.io/paulrudin/livefpl:0.0.22 # {"$imagepolicy": "flux-system:livefpl"}
        imagePullPolicy: IfNotPresent
        name: livefpl
        ports:
        - containerPort: 8000
          name: http
        stdin: false
        tty: false
        volumeMounts: []
      imagePullSecrets:
      - name: ghcrcred
      initContainers: []
      terminationGracePeriodSeconds: 30
      volumes: []
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  labels:
    name: livefpl
  name: livefpl
spec:
  rules:
  - host: livefpl.xamaral.com
    http:
      paths:
      - backend:
          serviceName: livefpl-ui
          servicePort: 8000
        path: /
  tls:
  - hosts:
    - livefpl.xamaral.com
    secretName: livefpl-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: livefpl
  name: livefpl
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    name: livefpl
  type: ClusterIP
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  labels:
    name: livefpl-ui
  name: livefpl-ui
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: livefpl-ui
  policy:
    semver:
      range: 0.0.x
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  labels:
    name: livefpl-ui
  name: livefpl-ui
  namespace: flux-system
spec:
  image: ghcr.io/paulrudin/livefpl-ui
  interval: 1m0s
  secretRef:
    name: ghcrcred
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  labels:
    name: livefpl
  name: livefpl
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: livefpl
  policy:
    semver:
      range: 0.0.x
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  labels:
    name: livefpl
  name: livefpl
  namespace: flux-system
spec:
  image: ghcr.io/paulrudin/livefpl
  interval: 1m0s
  secretRef:
    name: ghcrcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: livefpl-ui
  name: livefpl-ui
spec:
  minReadySeconds: 30
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: livefpl-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations: {}
      labels:
        name: livefpl-ui
    spec:
      containers:
      - args: []
        env:
        - name: API_URL
          value: http://livefpl:8000
        - name: HOST
          value: https://livefpl.xamaral.com
        - name: PORT
          value: "8000"
        image: ghcr.io/paulrudin/livefpl-ui:0.0.42 # {"$imagepolicy": "flux-system:livefpl-ui"}
        imagePullPolicy: IfNotPresent
        name: livefpl-ui
        ports:
        - containerPort: 8000
          name: http
        stdin: false
        tty: false
        volumeMounts: []
      imagePullSecrets:
      - name: ghcrcred
      initContainers: []
      terminationGracePeriodSeconds: 30
      volumes: []
